# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2017-2025 Georg K. H. Madsen, Jesús Carrete, Matthieu J. Verstraete
# Copyright (C) 2026 Hiroharu Sugawara (Julia port)
# Part of BoltzTraP.jl - Port of BoltzTraP2/tests

using BoltzTraP
using Test
using StaticArrays
using LinearAlgebra

# Try to load optional dependencies
const HAS_NPZ = try
    using NPZ
    true
catch
    @warn "NPZ not available, some tests will be skipped"
    false
end

# Check if reftest data is available (generated by Python BoltzTraP2)
const REFTEST_DATA_DIR = joinpath(@__DIR__, "..", "reftest", "data")
const HAS_REFTEST_DATA = isfile(joinpath(REFTEST_DATA_DIR, "si_interpolation.npz"))
if !HAS_REFTEST_DATA
    @warn "Reftest data not found at $REFTEST_DATA_DIR. Run reftest/generate_*.py to generate."
end

@testset "BoltzTraP.jl" begin

    @testset "Units" begin
        # Test numeric unit conversion constants
        @test BoltzTraP.BOHR_TO_ANG ≈ 0.529177210903 rtol=1e-10
        @test BoltzTraP.HA_TO_EV ≈ 27.211386245988 rtol=1e-10
        @test BoltzTraP.KB_AU ≈ 3.166811563e-6 rtol=1e-6
    end

    @testset "Equivalences" begin
        # Test lattice points in sphere
        lattvec = SMatrix{3,3,Float64}(I)  # Identity (cubic)
        radius = 2.0
        bounds = (2, 2, 2)

        points, sqnorms = BoltzTraP.lattice_points_in_sphere(lattvec, radius, bounds)

        # Origin should be included
        @test SVector(0, 0, 0) in points

        # All points should have norm ≤ radius
        for p in points
            @test norm(p) <= radius + 1e-10
        end

        # Points should be sorted by squared norm
        @test issorted(sqnorms)
    end

    @testset "Fermi-Dirac" begin
        # Test Fermi-Dirac distribution
        ε = collect(-5.0:0.1:5.0)
        μ = 0.0
        kT = 1.0

        f = BoltzTraP.fermi_dirac(ε, μ, kT)

        # f(μ) = 0.5
        @test f[findfirst(ε .≈ 0.0)] ≈ 0.5 rtol=1e-10

        # f(-5) ≈ 1, f(+5) ≈ 0 (not exactly ∞, so allow some tolerance)
        @test f[1] ≈ 1.0 atol=0.01
        @test f[end] ≈ 0.0 atol=0.01

        # Derivative at μ
        df = BoltzTraP.dfermi_dirac_de(ε, μ, kT)
        @test df[findfirst(ε .≈ 0.0)] ≈ -0.25 / kT rtol=1e-10
    end

    @testset "Interpolation" begin
        # Test phase factor computation
        kpoints = [0.0 0.0 0.0; 0.5 0.0 0.0; 0.0 0.5 0.0]
        equivalences = [zeros(Int, 1, 3), [1 0 0; -1 0 0]]

        phase = BoltzTraP.compute_phase_factors(kpoints, equivalences)

        # Phase for R=0 should be 1
        @test all(phase[:, 1] .≈ 1.0)
    end

    # I/O tests (no NPZ dependency)
    include("test_io_vasp.jl")
    include("test_io_qe.jl")
    include("test_spintype_metadata.jl")

    # Type tests
    include("test_types.jl")
    include("test_dftdata_integration.jl")

    # Structure validation tests (requires BoltzTraP2-public data)
    if isdir(joinpath(@__DIR__, "..", "..", "BoltzTraP2-public", "data"))
        include("test_structure_validation.jl")
        include("test_loader_detection.jl")
    end

    # Loader reference tests (requires NPZ and BoltzTraP2-public data)
    if HAS_NPZ && isdir(joinpath(@__DIR__, "..", "..", "BoltzTraP2-public", "data"))
        include("test_loaders_reftest.jl")
    end

    # Include additional test files if NPZ is available
    if HAS_NPZ
        include("test_sphere.jl")
        include("test_fd.jl")
    end

    # Include reftest-dependent tests only if data is available
    if HAS_NPZ && HAS_REFTEST_DATA
        include("test_fite.jl")
        include("test_bandlib.jl")
        include("test_calc_N_solve_mu.jl")
    end

    # DFTK extension tests (only if DFTK is available)
    # Note: These tests are slow due to SCF calculation, skip in CI by default
    if get(ENV, "TEST_DFTK", "false") == "true"
        include("test_dftk_extension.jl")
    end

end
